apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ .Values.cluster.name }}-{{ .Values.pool.worker.name }}
  namespace: fleet-default
boot2dockerUrl: ""
cfgparam:
- disk.enableUUID=TRUE
cloneFrom:  {{ .Values.vcenter.template }}
cloudConfig: |
  #cloud-config
  runcmd: 
    - "bash /root/cloudinit.sh"
    
  write_files: 
    - 
      content: |
          #!/bin/bash
          
          
          
          /usr/bin/vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv
          IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          
          SubnetMask=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          
          CIDR=$(ipcalc $IPAddress/$SubnetMask|grep "^Netmask"|awk '{print $4}') 
          Gateway=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          
          DNSSearch=$(sed -n 's/.*Property oe:key="guestinfo.dnssearch.servers" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          
          DNS=$(sed -n 's/.*Property oe:key="guestinfo.dns.servers" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
          
          nmcli con add con-name static ifname eth0 type ethernet ip4 $IPAddress/$CIDR gw4 $Gateway ipv4.dns "$DNS" ipv4.dns-search "$DNSSearch"
          
          nmcli con mod static ipv6.method disabled
          nmcli con up static
          
          hostnamectl set-hostname $(hostname).vi.pp.in.phm.education.gouv.fr
          
          /usr/sbin/subscription-manager unregister
          
          /usr/sbin/subscription-manager clean
          
          /usr/bin/rm /etc/yum.repo.d/* -f
          
          /usr/bin/yum remove katello* -y
          
    
          /usr/bin/curl -sS  'https://pr-sti-sat01.tec.pp.in.phm.education.gouv.fr/register?activation_keys=ak-qa-rhel-8x&force=true&hostgroup_id=844&location_id=4&organization_id=1&setup_insights=false' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE3MDA4MzczMzAsImp0aSI6ImU1YWNlODBiNjU0MDIyMzMyODFhOGQ4YzZlYjc2MWY2OWUyNGMyZDc2OGJjZjVmNmJmYzlhMWVmNzFiMzhmZDciLCJleHAiOjIwMTYxOTczMzAsInNjb3BlIjoicmVnaXN0cmF0aW9uI2dsb2JhbCByZWdpc3RyYXRpb24jaG9zdCJ9.FOtPw0VUB5VRk4_aRs9wyo_jcAGppWUxpMXEGosM0zQ' | bash > /dev/null 2>&1 > /root/log_registersat.log
          
          /usr/bin/sleep 30
          
          
          
          
      path: /root/cloudinit.sh
      permissions: "0755"
cloudinit: ""
common:
  labels: null
  taints: []
contentLibrary: ""
#cpuCount: {{ .Values.pool.worker.vmcpu | quote }}
{{- if eq (regexFind "^\\S*" .Values.pool.worker.vmbasket) "SMALL" }}
cpuCount: {{ .Values.pool.worker.vmsmallcpu | quote }}
{{- else }}
cpuCount: {{ .Values.pool.worker.vmstandardcpu | quote }}
{{- end }}

creationType: template

customAttribute: []

datacenter: {{ .Values.vcenter.datacenter }}

datastore: {{ .Values.vcenter.datastore }}

diskSize: {{ .Values.pool.worker.vmdisk | quote }}

folder: {{ .Values.vcenter.folder }}

hostsystem: {{ .Values.pool.worker.host }}

#memorySize: {{ .Values.pool.worker.vmram | quote }}
{{- if eq (regexFind "^\\S*" .Values.pool.worker.vmbasket) "SMALL" }}
memorySize: {{ .Values.pool.worker.vmsmallram | quote }}
{{- else }}
memorySize: {{ .Values.pool.worker.vmstandardram | quote }}
{{- end }}

network:
# on peut mettre directement : /vRack-Datacenter/network/vxw-dvs-9-virtualwire-433-sid-10067-LS-KUB-WRK-01 |si ça fonctionne pas avec regex 
## regex ^\S* 
- {{ .Values.vcenter.datacenter }}/network/{{ regexFind "^\\S*" .Values.pool.worker.vlan }}
os: linux
pool: {{ .Values.vcenter.pool }}

vappIpallocationpolicy: fixedAllocated
vappIpprotocol: IPv4
vappProperty:
- guestinfo.interface.0.ip.0.address=ip:{{ regexFind "^\\S*" .Values.pool.worker.vlan }}
- guestinfo.interface.0.ip.0.netmask=${netmask:{{ regexFind "^\\S*" .Values.pool.worker.vlan }}}
- guestinfo.interface.0.route.0.gateway=${gateway:{{ regexFind "^\\S*" .Values.pool.worker.vlan }}}
- guestinfo.dns.servers=${dns:{{ regexFind "^\\S*" .Values.pool.worker.vlan }}}
- guestinfo.dnssearch.servers=${dns:{{ regexFind "^\\S*" .Values.pool.worker.vlan }}}
vappTransport: com.vmware.guestInfo
vcenter: {{ .Values.vcenter.host }}
vcenterPort: "443"
