cloudprovider: "rancher-vsphere"

s3:
  endpoint: "storagegrid.in.phm.education.gouv.fr"
  region: "eu-west-3"

http_proxy: "http://proxy.tec.in.phm.education.gouv.fr:3128"
https_proxy: "http://proxy.tec.in.phm.education.gouv.fr:3128"
no_proxy: "127.0.0.1,localhost,10.0.0.0/8,.cluster.local,cattle-system.svc,.svc"

vcenter:
  proxy: ""
  host: "pr-sti-vcenter22.vi.pp.in.phm.education.gouv.fr"
  pool: /DC_OSN_PHM_PP_01/host/CCL_OSN_PHM_PP_STD_01/Resources
  folder: /DC_OSN_PHM_PP_01/vm/VM_OSN_PHM_PP/VM_OSN_PHM_PP_K8S
  template: /DC_OSN_PHM_PP_01/vm/VM_OSN_PHM_PP/TMP_OSN_PHM_PP_RCH/TEMPLATE-PP-RHEL8X-RKE2-v3
  datacenter: /DC_OSN_PHM_PP_01
  username: "svc-k8s-pp-sto@vsphere.local"
  datastore: /DC_OSN_PHM_PP_01/datastore/DC_OSN_PHM_PP_STD_K8S_01/V_OSN_PHM_PP_STD_01_CHS22001_2T_K8S_00057
  datastoreURL: "ds:///vmfs/volumes/65b2c79a-35fe2720-d38d-78ac448783d2/"
  allowVolumeExpansion: true

pool:
  controlplane:
    name: "mst"
    etcd: true
    controlplane: true
    worker: false
    vmcpu: 2
    vmsmallcpu: 2
    vmstandardcpu: 4
    vmram: 8192
    vmsmallram: 8192
    vmstandardram: 16384
    vmdisk: 20000
    host: ""
    vlan: "DPG_OSN_PHM_PP_STD_01_VLAN-4017"

  worker:
    name: "wrk"
    etcd: false
    controlplane: false
    worker: true
    vmcpu: 4
    vmsmallcpu: 4
    vmstandardcpu: 8
    vmram: 16384
    vmsmallram: 16384
    vmstandardram: 32768
    vmdisk: 20000
    host: ""
    vlan: "DPG_OSN_PHM_PP_STD_01_VLAN-4018"

  # enable monitoring
monitoring:
  enabled: true
  values:
    prometheus:
      prometheusSpec:
        evaluationInterval: 1m
        resources:
          limits:
            cpu: 3000m
            memory: 25000Mi
          requests:
            cpu: 2000m
            memory: 14000Mi
        retention: 15d
        retentionSize: 50GiB
        scrapeInterval: 1m
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: vsphere-csi-sc

  # enable logging
logging:
  enabled: true

  # enable logging
gatekeeper:
  enabled: true

